-- 1. Table for Client Notes (CRM)
CREATE TABLE IF NOT EXISTS public.client_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id UUID REFERENCES public.clientes(id) ON DELETE CASCADE, -- Assuming 'clientes' uses UUID
    note TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.client_notes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for public" ON public.client_notes FOR ALL USING (true) WITH CHECK (true);

-- 2. Add 'metadata' column to 'clientes' if it doesn't exist (flexible storage)
-- 2. Table for Client Profiles (Extended Data: Birthday, Tags)
CREATE TABLE IF NOT EXISTS public.client_profiles (
    client_id UUID REFERENCES public.clientes(id) ON DELETE CASCADE PRIMARY KEY,
    birth_date DATE,
    tags TEXT[], -- Array of strings e.g. ['VIP', 'Vegetarian']
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.client_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for public profiles" ON public.client_profiles FOR ALL USING (true) WITH CHECK (true);

