-- ESTRUCTURA DE BASE DE DATOS - YOKO POKE HOUSE
-- Basado en el menú oficial de imágenes.

-- 1. TABLA DE TAMAÑOS (Configuración de precios y límites)
drop table if exists sizes cascade;
create table sizes (
  id bigint generated by default as identity primary key,
  name text not null, -- 'Mediano', 'Grande'
  base_price numeric not null,
  
  -- LÍMITES (Cuántos incluye gratis)
  included_proteins integer default 1,
  included_toppings integer default 3, -- Vegetales/Frescos
  included_crunches integer default 2, -- Secos
  included_sauces integer default 1,
  
  -- PRECIOS EXTRA (Costo si te pasas del límite)
  price_extra_protein numeric default 40,
  price_extra_topping numeric default 25,
  price_extra_crunch numeric default 15,
  price_extra_sauce numeric default 15
);

-- 2. TABLA DE INGREDIENTES (Partes del Bowl)
drop table if exists ingredients cascade;
create table ingredients (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null, -- 'base', 'protein', 'topping', 'crunch', 'sauce'
  icon text,
  is_premium boolean default false, -- Si tiene costo extra siempre (ej. Salmón vs Surimi)
  premium_price numeric default 0,
  is_available boolean default true,
  stock integer default 100 -- Management of portions
);

-- 3. TABLA DE MENU EXTRA (Sides, Drinks, Postres, Signature Bowls)
drop table if exists menu_items cascade;
create table menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null, -- 'signature_bowl', 'side', 'drink', 'dessert'
  description text,
  price numeric not null,
  image_url text,
  is_available boolean default true,
  stock integer default 100 -- Management of units
);

-- 4. TABLA DE PEDIDOS
drop table if exists orders cascade;
create table orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text,
  customer_phone text,
  delivery_address text, -- Explicit column for address
  delivery_method text default 'pickup', -- pickup/delivery
  payment_method text default 'cash',
  total numeric,
  items jsonb, -- Renamed from order_details for consistency
  status text default 'pending' -- pending, preparing, completed, cancelled
);

-- 5. TABLA DE REGLAS (CONDICIONALES AVANZADOS)
drop table if exists ingredient_rules cascade;
create table ingredient_rules (
  id bigint generated by default as identity primary key,
  trigger_id bigint references ingredients(id), -- If this ingredient is selected...
  action text not null, -- 'ban' (disable), 'require' (must select), 'alert' (show msg)
  target_id bigint references ingredients(id), -- ...do this to this ingredient
  message text -- Optional message to user
);


-- ==========================================
-- DATOS SEMILLA (INSERT DATA)
-- ==========================================

-- TAMAÑOS (Según imagen "Arma tu poke")
insert into sizes (name, base_price, included_proteins, included_toppings, included_crunches, included_sauces, price_extra_protein, price_extra_topping, price_extra_crunch, price_extra_sauce) values
('Mediano', 145, 1, 3, 2, 1, 40, 25, 15, 15),
('Grande',  165, 2, 4, 2, 2, 40, 25, 15, 15);


-- INGREDIENTES

-- Bases
insert into ingredients (name, type, icon) values
('Arroz Blanco', 'base', '🍚'),
('Arroz Negro', 'base', '🌾'), -- Asumiendo icono
('Noodles de Vegetal', 'base', '🍝'); -- Icono healthy

-- Proteínas (Agrega extra por $40 es general, pero si alguno es premium base se pone precio)
-- En la imagen dice "Agrega extra por $40" abajo de la lista, implica que es el costo de la adicional.
insert into ingredients (name, type, icon) values
('Atún Fresco', 'protein', '🐟'),
('Spicy Tuna', 'protein', '🌶️'),
('Arrachera', 'protein', '🥩'),
('Pollo al Grill', 'protein', '🍗'),
('Pollo Teriyaki', 'protein', '🍱'),
('Sweet Salmon', 'protein', '🍯'),
('Kanikama', 'protein', '🦀');

-- Toppings (Frescos) - Extra $25
insert into ingredients (name, type, icon) values
('Pepino', 'topping', '🥒'),
('Aguacate', 'topping', '🥑'),
('Mango', 'topping', '🥭'),
('Zanahoria', 'topping', '🥕'),
('Elotes', 'topping', '🌽'),
('Pimiento', 'topping', '🫑'),
('Edamames', 'topping', '🫛'),
('Tomate Cherry', 'topping', '🍅'),
('Queso Philadelphia', 'topping', '🧀');

-- Crunch (Secos) - Extra $15
insert into ingredients (name, type, icon) values
('Almendra Fileteadas', 'crunch', '🌰'),
('Won Ton', 'crunch', '🥟'),
('Cacahuate Garapiñado', 'crunch', '🥜'),
('Cacahuate', 'crunch', '🥜'),
('Banana Chips', 'crunch', '🍌'),
('Betabel Bacon', 'crunch', '🥓'),
('Maicito Enchilado', 'crunch', '🌶️'),
('Maicito', 'crunch', '🌽');

-- Salsas - Extra $15
insert into ingredients (name, type, icon) values
('Soya', 'sauce', '🥢'),
('Siracha', 'sauce', '🔥'),
('Ponzu', 'sauce', '🍋'),
('Mango Habanero', 'sauce', '🥭'),
('Mayo Ajo', 'sauce', '🧄'),
('Mayo Cilantro', 'sauce', '🌿'),
('Anguila', 'sauce', '🍯'),
('Olive Oil', 'sauce', '🫒'),
('Habanero Drops', 'sauce', '💧'),
('Cacahuate', 'sauce', '🥜'),
('Agridulce', 'sauce', '🏺');


-- MENU ITEMS (Sides, Drinks, Desserts)

-- Share & Smile (Sides)
insert into menu_items (name, category, price, description) values
('Edamames', 'side', 100, 'Vainas de edamame salteadas en ajonjolí oil, toque de limón y salsas orientales'),
('Pollo al Grill', 'side', 150, 'Pollo a la plancha acompañado de un mix de verduras de temporada y un scoop de arroz'),
('Torre Won Ton', 'side', 135, 'Atún fresco en salsa de mayo siracha acompañado de aguacate y pepino, servido en crujientes láminas de won ton'),
('Kushiagues', 'side', 110, 'Crujientes empanizados al estilo japonés rellenos de Queso o Plátano'),
('Rollos Vietnamita', 'side', 120, 'Rollos fritos rellenos de vegetales salteados en salsas orientales y queso derretido'),
('Green Rolls', 'side', 115, 'Verduras de temporada envueltas en una delicada hoja de papel arroz fresco'),
('Papas Trufadas', 'side', 250, 'Papas gajo bañadas en aceite de trufa, queso parmesano y especias de la casa, acompañadas de mermelada de tocino y pork belly bites'),
('Camarones Panko', 'side', 150, 'Camarones empanizados al estilo japonés servidos con nuestra salsa de temporada'),
('Gyozas', 'side', 120, 'Deliciosas gyozas salteadas en un preparado oriental');

-- Drinks
insert into menu_items (name, category, price) values
('Water People', 'drink', 35),
('Refresher del día', 'drink', 50),
('Café', 'drink', 35),
('Agua Embotellada', 'drink', 25),
('Coca Cola', 'drink', 35),
('Coca Cola Light', 'drink', 35),
('Soda Japonesa', 'drink', 35),
('Monster Zero', 'drink', 48),
('Modelo Especial', 'drink', 45),
('Modelo Negra', 'drink', 45),
('Modelo Negra 0%', 'drink', 45),
('Lucky Buddha Beer', 'drink', 85);

-- Postres
insert into menu_items (name, category, price, description) values
('By GERANIO', 'dessert', 110, 'Postres contemporáneos basados en la temporalidad e innovación en la alta repostería.'),
('Helado Artesanal', 'dessert', 95, 'Sabores de temporada'),
('Mochis', 'dessert', 100, 'Bocaditos dulces de arroz con una textura elástica inconfundible.');
